stevearc/conform.nvim

README.md
lua/conform/formatters/ruff.lua

This commit will add support for `ruff --fix`.

feat: ruff

---

README.md
doc/conform.txt
lua/conform/init.lua
lua/conform/runner.lua
scripts/options_doc.lua
tests/runner_spec.lua

feat: allow running commands in a shell

---

README.md
doc/conform.txt
lua/conform/formatters/rustywind.lua

This adds rustywind, a CLI for organizing Tailwind CSS classes.

Feat: Add rustywind formatter

---

lua/conform/formatters/squeeze_blanks.lua

feat: add `squeeze_blanks`

---

lua/conform/formatters/astyle.lua

- Added the support for astyle formatter

feat(astyle): Add support for astyle

---

README.md
lua/conform/formatters/google-java-format.lua

feat: add 'google-java-format' formatter

---

lua/conform/formatters/mix.lua

I think this one is pretty straight forward to add. I've tested this locally but let me know if I missed anything.

add support for mix format

---

lua/conform/just.lua

Add a formatter for [justfile](https://github.com/casey/just)

feat: add just

---

lua/conform/formatters/injected.lua

closes #111
This changes the indentation logic to handle blockquotes in markdown

fix: injected formatter handles markdown code blocks in blockquotes

---

README.md
doc/conform.txt
lua/conform/formatters/easy-coding-standard.lua

Add ecs php formatter ([easy-coding-standard](https://github.com/easy-coding-standard/easy-coding-standard))

feat: add easy-coding-standard

---

README.md
doc/conform.txt
lua/conform/formatters/fixjson.lua

Added the [fixjson](https://github.com/rhysd/fixjson) formatter
Not sure if you require more information than this?
I tested it out locally, and it worked at least :-)
Best,
Magnus

[feat] Added fixjson

---

lua/conform/formatters/rubyfmt.lua

https://github.com/fables-tales/rubyfmt

Add rubyfmt for formatting Ruby

---

lua/conform/formatters/blue.lua

API is the same with Black formatter

Add blue formatter

---

README.md
doc/conform.txt
doc/recipes.md
lua/conform/formatters/injected.lua
lua/conform/init.lua
lua/conform/util.lua
scripts/options_doc.lua

#138
Experimenting with having the formatters configs merge with the base config. ~~Functionality is done; needs some rework of the docs.~~
Docs have been reworked. While this does make things a bit more complicated to reason about, the wins here for ease of configuration are significant. We're going to ship it

feat!: merge configs in conform.formatters with defaults

---

README.md
lua/conform/formatters/zprint.lua

https://github.com/kkinnear/zprint
For the config flags used here, see https://github.com/kkinnear/zprint/blob/ce5a1caf676b00f2b754e35151042211fbcc57f8/doc/reference.md?plain=1#L3727-L3745

feat: zprint formatter for clojure

---

doc/advanced_topics.md

docs: fix typo in doc/advanced_topics.md

---

lua/conform/formatters/gn.lua

Adding support for GN build file formatting via stdin.

Add gn build file format cmd

---

README.md
doc/conform.txt
lua/conform/formatters/usort.lua

feat: add usort

---

README.md
lua/conform/formatters/typstfmt.lua

Adds support for [typstfmt](https://github.com/astrale-sharp/typstfmt/).

feat: add typstfmt

---

lua/conform/init.lua

fixes #173
fixes #181
Hack to work around https://github.com/neovim/neovim/issues/21856

fix: nonzero exit code on :wq

---

README.md
lua/conform/formatters/pangu.lua

Add support for [pangu](https://github.com/vinta/pangu.py)

feat: add pangu

---

README.md
lua/conform/formatters/styler.lua

This adds a formatter for the R programming language using [styler](https://github.com/r-lib/styler) via [r.nvim](https://github.com/devOpifex/r.nvim)

feat: add styler formatter for R

---

README.md
lua/conform/formatters/auto_optional.lua

A Python tool. Quite useful for lazy people like me ;)
Unfortunately, I noticed that using this tool might require user to increase the timeout. This doesn't happen in null-ls, but that's for another story.

feat: add `auto-optional`

---

README.md
doc/conform.txt
lua/conform/formatters/phpinsights.lua

feat: add phpinsights

---

lua/conform/formatters/injected.lua

fix: injected formatter adds language to file extension

---

lua/conform/formatters/fourmolu.lua

Add Fourmolu for haskell code

---

lua/conform/formatters/typos.lua

it's a codespell alternative that looks promising

feat: add `typos`

---

README.md
lua/conform/formatters/buildifier.lua

See https://github.com/bazelbuild/buildtools/tree/master/buildifier for what the tool is and what it does.

[formatter] Add support for buildifier

---

lua/conform/formatters/biome.lua

biome 1.4.0 has been released, which fixes the emoji-bug. so that PR #120 can be reverted.

chore(biome): revert temp. non-stdin use due to upstream fix (v.1.4.0)

---

lua/conform/formatters/biome.lua
lua/conform/formatters/standardjs.lua

Modified the Biome formatter to use util.from_node_modules() for executable selection, ensuring local node_modules executables are prioritized according to project settings.

Improved Biome formatter with util.from_node_modules

---

lua/conform/formatters/asmfmt.lua

Add [asmfmt](https://github.com/klauspost/asmfmt)

feat: add asmfmt

---

lua/conform/formatters/injected.lua
tests/injected/combined_injections.md.formatted

refactor(injected): use included_regions instead of private methods

---

README.md
lua/conform/formatters/rescript-format.lua

Adds the [ReScript](https://rescript-lang.org/) formatter

feat: add ReScript formatter

---

lua/conform/formatters/twig-cs-fixer.lua

add [twig-cs-fixer](https://github.com/VincentLanglet/Twig-CS-Fixer)

feat: add twig-cs-fixer

---

README.md
lua/conform/formatters/liquidsoap-prettier.lua

A formatter for https://www.liquidsoap.info/ 😄

feat(formatter): liquidsoap-prettier

---

README.md
doc/formatter_options.md
lua/conform/formatters/rustfmt.lua

An alternative to #321
closes #320

fix(rustfmt): use Cargo.toml settings and default to recent edition

---

lua/conform/formatters/injected.lua
tests/injected/inline.ts
tests/injected/inline.ts.formatted

fix(injected): ignore indentation of final whitespace line

---

README.md
doc/conform.txt
lua/conform/formatters/roc.lua

Adds support for formatting [Roc](https://roc-lang.org) code using `roc format`.

feat: add support for roc format

---

lua/conform/formatters/bicep.lua

This PR adds a new formatter "bicep" for the [Bicep](https://github.com/Azure/bicep) language.

feat: add support for bicep

---

README.md
lua/conform/formatters/verible.lua

This is a common tool used by those who write SystemVerilog HDL. This PR adds it to the formatter list.

Add verible formatter for SystemVerilog

---

lua/conform/formatters/biome-check.lua
lua/conform/formatters/biome.lua

> Biome now accepts the biome.jsonc file as configuration
https://biomejs.dev/blog/biome-v1-6/#support-for-biomejsonc

fix(biome): support biome.jsonc file

---

README.md
doc/conform.txt
lua/conform/formatters/hindent.lua

Adds support for Haskell formatter hindent

feat(haskell): support hindent

---

README.md
doc/conform.txt
lua/conform/formatters/fprettify.lua

Adds support for Fortran formatter fprettify

feat(fortran): support fprettify

---

README.md
doc/conform.txt
lua/conform/formatters/efmt.lua

Adds support for Erlang formatter efmt

feat(erlang): support efmt

---

README.md
doc/conform.txt
lua/conform/formatters/findent.lua

Adds support for the Fortran formatter findent.

feat(fortran): support findent

---

README.md
doc/conform.txt
lua/conform/formatters/pyink.lua

Adds support for the Python formatter pyink

feat(python): support pyink

---

lua/conform/formatters/rstfmt.lua

Not to be confused with rustfmt

feat(rst): support rstfmt

---

lua/conform/formatters/docstrfmt.lua

feat: support docstrfmt

---

README.md
doc/conform.txt
lua/conform/formatters/cljfmt.lua

I added config for yet one Clojure formatting tool. Unfortunately, I haven't found contribution docs, so I tried to use common sense.

Add support for cljfmt

---

lua/conform/runner.lua

I needed this as a workaround to paths that include () on windows for prettierd. Svelte layout groups. A simple enough solution to that problem.

Add support to extensions to arguments.

---

lua/conform/formatters/kulala-fmt.lua

kulala-fmt is an opinionated .http and .rest files linter and formatter.
x-ref: https://github.com/mistweaverco/kulala-fmt/issues/12

feat: add kulala-fmt

---

lua/conform/formatters/mojo_format.lua

feat: add mojo format

---

README.md
doc/conform.txt
lua/conform/formatters/kdlfmt.lua

feat: add support for kdlfmt

---

lua/conform/formatters/ufmt.lua

feat: support ufmt

---

lua/conform/formatters/prettier.lua
lua/conform/formatters/prettierd.lua

continues https://github.com/stevearc/conform.nvim/pull/564
addresses https://github.com/stevearc/conform.nvim/pull/567
supersedes https://github.com/stevearc/conform.nvim/pull/570

fix(prettier): respect "prettier" config field in "package.json"

---

lua/conform/formatters/syntax_tree.lua

Adds SyntaxTree as another option to format Ruby.

Add syntax_tree

---

lua/conform/formatters/commitmsgfmt.lua

```
formatters_by_ft = {
...
gitcommit = {"commitmsgfmt"},
}
```

feat: add commitmsgfmt

---

lua/conform/formatters/stylua.lua

fix: Add `--respect-ignores` to the stylua command

---

lua/conform/formatters/nph.lua

Adds support for [nph](https://github.com/arnetheduck/nph), a code formatter for the nim programming language

feat: support nph

---

lua/conform/formatters/csharpier.lua

fix: update csharpier

---

lua/conform/formatters/reformat-gherkin.lua

feat: support reformat-gherkin

---

README.md
doc/conform.txt
lua/conform/formatters/ansible-lint.lua

I set async since ansible lint takes a lot of time to execute, depending on the file/environment.

feat: ansible-lint

---

README.md
lua/conform/formatters/golangci-lint.lua

Add new formatter: golangci-lint fmt. It was released 3 days ago.

feat: add golangci-lint fmt

---

lua/conform/lsp_format.lua

```
- WARNING client.request_sync is deprecated. Feature will be removed in
Nvim 0.13
- ADVICE:
- use client:request_sync instead.
- stack traceback:
*/lazy/conform.nvim/lua/conform/lsp_format.lua:155
*/lazy/conform.nvim/lua/conform/init.lua:532
```

fix: elimante deprecated warings on nightly

---

lua/conform/formatters/odinfmt.lua

A definition for the odinfmt program in formatters.

add formatter definition for odinfmt

---

README.md
doc/conform.txt
lua/conform/formatters/typespec.lua

Adds support for [TypeSpec formatter](https://typespec.io/docs/handbook/formatter/).

feat: add support for typespec

---

lua/conform/formatters/treefmt.lua

https://github.com/stevearc/conform.nvim/issues/701
idk if this is wanted at all, but treefmt does have its own option I need to work on, but treefmt is designed to be per-repo?

feat: inital support for treefmt formatter

---

lua/conform/formatters/biome-organize-imports.lua

biome v2 changed its command for organize imports.

fix: biome v2 organize imports

---

lua/conform/formatters/sqruff.lua

It has been removed in the latest version

fix(sqruff): remove `--force` flag

---

README.md
doc/conform.txt
lua/conform/formatters/tombi.lua

Adds support for the tombi TOML formatter + linter.

feat: add support for tombi

---

README.md
lua/conform/formatters/ghokin.lua

This PR adds the [ghokin] formatter.
[ghokin]: https://github.com/antham/ghokin

feat: add ghokin formatter for cucumber files

---

README.md
lua/conform/formatters/keep-sorted.lua

This PR adds the [keep-sorted] formatter.
[keep-sorted]: https://github.com/google/keep-sorted

feat: add keep-sorted

---

lua/conform/formatters/qmlformat.lua

Add [`qmlformat`](https://doc.qt.io/qt-6//qtqml-tooling-qmlformat.html) formatter for QML files.

feat: add qmlformat for QML files

---

README.md
lua/conform/formatters/biome-check.lua
lua/conform/formatters/biome-organize-imports.lua
lua/conform/formatters/biome.lua

This PR adds a little more information about the biome configurations as this seems to be a common misunderstanding people have.
Related to #585

docs: expand descriptions for biome configurations
