stevearc/conform.nvim

README.md
lua/conform/formatters/fish_indent.lua

This PR adds fish_indent from [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/fish_indent.lua).

[formatter] fish_indent

---

lua/conform/init.lua
lua/conform/runner.lua
lua/conform/util.lua
tests/options_doc.lua

For #9 
Now by default if a format command errors, we will notify the user. Successive failures will not notify until there is at least one success. This can be disabled by either setting `notify_on_error = false` in the setup options, or by passing `quiet = true` to `conform.format()`.

feat: notify when formatter errors, and add notify_on_error config option

---

lua/conform/health.lua
lua/conform/init.lua
lua/conform/log.lua
lua/conform/runner.lua
lua/conform/util.lua
tests/fuzzer_spec.lua
tests/runner_spec.lua

This means we can leverage all of the work that was done in the LSP client to preserve marks, cursor position, etc

feat: apply changes as text edits using LSP utils

---

README.md
scripts/options_doc.lua

fix config error, and add a tip for formatters list
Oh, it is `prettierd`, not `prettier_d`, it gives is that "No config found". At first I thought it was because the configuration of pretter was not given.
Then I started to troubleshoot my configuration file, and finally I found out that the sample configuration in the readme was wrong 🥹

fix readme error and add a tip

---

lua/conform/health.lua

The `report_` health functions have been deprecated, and so this PR updates the health check to use the newer versions of the reporters if available.

fix(health): use non-deprecated functions if available

---

lua/conform/formatters/indent.lua

Hi,
Wonderful plugin! Thank you. This PR adds `indent` which is a C formatter.
On a typical GNU/Linux system there's a good chance GNU Indent is preinstalled and if you're on a BSD system (such as OpenBSD) there's the BSD version of the `indent` program.
Edit: I wasn't sure if the meta data could be omitted so I added the GNU information (since it's the most common and widely available).

feat: add GNU/BSD indent

---

README.md
doc/conform.txt
lua/conform/init.lua
scripts/options_doc.lua

Following up on #31, #33
I wasn't completely happy with the earlier solution. If you want to run `{ "trim_whitespace" }` on all filetypes but still use LSP formatting, you would have to pass `lsp_fallback = "always"`. But if you _didn't_ want LSP formatting on filetypes where you have formatters configured, you would have to write a helper function to do some detection of the filetype and determine if you want to pass in `true` or `"always"` (#36). I think that the _common case_ for formatting is:
- Configure specific formatters to use for some filetypes, don't use LSP
- For non-configured filetypes, default to using LSP formatting
- If no LSP formatting is available, maybe use some generic formatters (e.g. `trim_whitespace`)
I would like to optimize for this common case. This PR makes it …

feat: make lsp_fallback behavior more intuitive

---

lua/conform/formatters/buf.lua

Noticed this was pointing to the `buf lint` docs - seemed like the `buf format` CLI reference might be better. An alternative might be the `buf format` [style reference](https://buf.build/docs/format/style), but that doesn't seem as good.

Change buf format URL

---

README.md
lua/conform/formatters/php_cs_fixer.lua

- Added a simple utility to check a list of paths and return the first that exists, or a default. Useful for defining commands for a formatter so it will call the correct executable.
- Added support for `php-cs-fixer`.

feat(php-cs-fixer): Add support for php-cs-fixer

---

lua/conform/formatters/darker.lua

[`darker`](https://github.com/akaihola/darker) runs [`black`](https://github.com/psf/black) only on the changed lines in a git repo. Useful in situations where the whole repo hasn't been painted black for one reason or another but you still want to be able to run autoformatter on changes you made.

feat: add darker

---

README.md
doc/conform.txt
doc/recipes.md
lua/conform/formatters/injected.lua
lua/conform/init.lua
lua/conform/runner.lua

New `injected` formatter that will find injected languages using treesitter and format those code snippets with the configured formatters. To use:
```lua
require("conform").setup({
formatters_by_ft = {
markdown = { "injected" },
}
})
```

feat: format injected languages

---

lua/conform/formatters/injected.lua

On nightly, the injected formatter doesn't work.
`parse(true)` needs to be used to parse injections.
See also https://github.com/folke/noice.nvim/pull/571
Caused by upstream change: https://github.com/neovim/neovim/commit/2ca076e45fb3f1c08f6a1a374834df0701b8d778

fix(injected): parse injections

---

lua/conform/formatters/phpcbf.lua

fix: phpcbf invalid stdin-path arguments

---

lua/conform/runner.lua

fix: typo in runner.lua

---

lua/conform/formatters/injected.lua
lua/conform/init.lua
lua/conform/runner.lua

closes #111
This adds a configuration option for users to optionally ignore errors in the injected formatter. To enable:
```lua
require("conform.formatters.injected").options.ignore_errors = true
```

feat: expose configuration options for injected formatter

---

lua/conform/formatters/biome.lua

Due to this bug (https://github.com/biomejs/biome/issues/455), using stdin will break some emojis. Until the bug is fixed, the biome formatter should therefore write the file in-place, since the bug does not occur in that case.

fix(biome): do not use stdin due to biome bug with emojis

---

README.md
doc/conform.txt
lua/conform/formatters/rufo.lua

full credits to stevearc  https://www.reddit.com/r/neovim/comments/175b984/comment/k4ggl2n

feat: add rufo support

---

lua/conform/formatters/shellcheck.lua

since we switched from `args` from a list of strings to a long string, we forgot that we also needed to quote the filename 🙈

fix: `shellcheck` filenames with space

---

README.md
lua/conform/formatters/pint.lua

This PR adds a preset for [laravel/pint](https://github.com/laravel/pint). A popular formatting tool for laravel. It has preconfigured configs for e.g. laravel and symfony code styling.
- Supports both mason and local composer install
I am not sure if using vim.fn.stdpath("data") to get to the mason install path is a good practice, as I am not too experienced with nvim scripting. Feel free to change

feat: Add config for laravel/pint

---

README.md
doc/conform.txt
lua/conform/formatters/markdownlint-cli2.lua

markdownlint-cli2 is a better cli for markdownlint. 
It allows having config files in different directories, and it's also from the same author as the original node.js markdownlint lib.

Add markdownlint-cli2

---

lua/conform/formatters/mdslw.lua

With this PR, I would like to suggest the addition of the markdown auto-formatter `mdslw`. I am already using `mdslw` with `conform.nvim` and was wondering whether it could be added to the official list of available tools. Before creating this PR, I was wondering whether there were any prerequisites for having an auto-formatter added to `conform.nvim`, but I could not find any information in the docs.
Disclaimer: I am the author of `mdslw` ([repo link](https://github.com/razziel89/mdslw)).
In some other PR, I read that only the lua files were mandatory and all the rest would be generated automatically. I hope I understood that correctly. If you would like to see any changes to this PR, please let me know and I will incorporate them. I would be grateful if you could consider this PR.

feat: add mdslw markdown formatter

---

README.md
lua/conform/formatters/cbfmt.lua

Added support for [cbfmt](https://github.com/lukas-reineke/cbfmt) formatter to format codeblocks inside markdown and org documents

feat: add cbfmt

---

lua/conform/formatters/standardjs.lua

I've removed the `$FILENAME` argument from the **standardjs** formatter configuration. It's not needed with the `--stdin` flag.

chore: remove $FILENAME from standardjs formatter config

---

lua/conform/formatters/jsonnetfmt.lua

Add support for jsonnetfmt. It's also available in Mason, so native conform.nvim support would be cool.

feat: add jsonnetfmt

---

lua/conform/formatters/injected.lua

Some formatters rely on information such as `filetype`. If that one of those formatters are used by the `injected` formatter, we need to load the buffer of the injected so that it calculates information such as `filetype`.
This also validates that `_injection_query` exists before enabling the `injected` formatter. Not all treesitter parsers provide this query if they do not have any possible language injections. One example of this is the `json` parser which doesn't have any injections. This will tell the parser that it doesn't actually need to run for buffers with parsers without injections.

fix: various fixes for the `injected` formatter

---

lua/conform/init.lua

This makes the behavior of formatexpr more consistent with
`vim.lsp.formatexpr`; do not run vim's builtin formatter.
Problem: When conform's formatexpr is used and (range or buffer) but
conform can't do formatting and there is no LSP server with the
formatting capabilities, it will fall back to the (wrong) built-in
formatting, which might result in simply concatenating all the words.
This is a breaking change (as a part of v5.0 with breaking change),
reverting the behavior introduced in 278bcd8bf2017e187e963b515017341fdd87fe2f (#55). /cc @cryptomilk

fix(formatexpr)!: do not fallback to the built-in formatter

---

lua/conform/formatters/prettier.lua

This is a work in progress for designing some nice to use options for `prettier` (and ideally `prettierd` at some point) to enable formatting using the `filetype` rather than filename. This helps when using files with non-traditional extensions (ex. `qmd` Quarto files, `rmd` R Markdown files) as well as injected code.
It also allows the user to easily configure prettier as well if a user wants to use a different javascript parser for example, prettier supports several different types just for that one file format.
The design here is definitely still up in the air and I am open to suggestions!
Potential ideas to explore:
- Having a simple list for mapping filetypes, extensions
- Having a full override function to allow the user to do arbitrary lua operations to derive the parser …

feat(prettier): add `options` for configuring prettier parser based on filetype

---

lua/conform/formatters/rubocop.lua

This ensures a much quicker execution on 2nd and any subsequent run. Otherwise there's always a 1-3 seconds delay before formatting is being applied (as rubocop is not that quick).
From rubocop's documentation:
```
--server If a server process has not been started yet, start the server process and execute inspection with server.
```
([documentation](https://docs.rubocop.org/rubocop/usage/server.html))
I've tested it locally with custom defined formatter and it resulted in a much quicker execution on subsequent runs. Best if someone else also tested this to confirm my observations.
An even better approach would be to use the [LSP server](https://docs.rubocop.org/rubocop/usage/lsp.html), but I'm not sure how to achieve that (specifying the `--lsp` option wipes the buffer on each conform run …

Execute rubocop via rubocop's server

---

README.md
lua/conform/formatters/fnlfmt.lua

Note: latest tagged version `0.3.1` contains a bug that causes the output to contain an extra newline at the end. This is fixed on upstream `main` branch and pending release: https://git.sr.ht/~technomancy/fnlfmt/commit/d8f950865a00dcabc092c39a1127144e0d62d0c4

feat: add fnlfmt formatter

---

.github/workflows/automation_remove_question_label_on_comment.yml
lua/conform/formatters/injected.lua
lua/conform/fs.lua
lua/conform/init.lua
lua/conform/runner.lua
run_tests.sh
tests/fake_formatter.sh
tests/injected/block_quote.md
tests/injected/block_quote.md.formatted
tests/injected/combined_injections.md
tests/injected/combined_injections.md.formatted
tests/injected/inline.ts
tests/injected/inline.ts.formatted
tests/injected/simple.md
tests/injected/simple.md.formatted
tests/injected_spec.lua
tests/minimal_init.lua
tests/runner_spec.lua
tests/test_util.lua

closes #224
closes #207
closes #229
Adds tests for the injected formatter, fixes some flappy tests, and adds support for injections that happen in the middle of a line.

fix: injected formatter handles inline injections

---

README.md
doc/conform.txt
lua/conform/formatters/xmllint.lua

Add a config for [xmllint](http://xmlsoft.org/xmllint.html) inspired by [none-ls](https://github.com/nvimtools/none-ls.nvim). 
Source: https://github.com/nvimtools/none-ls.nvim/blob/main/lua/null-ls/builtins/formatting/xmllint.lua

feat: add xmllint formatter

---

lua/conform/runner.lua
tests/fuzzer_spec.lua
tests/runner_spec.lua

Fixes #249 
This fix checks for blank formatter output in `apply_format`. Not sure if this is the best place to apply this fix, but seemed  the most obvious place since it'll work the same for both sync and async formats

Fix(black): formatting excluded files results in blank buffer (#249)

---

lua/conform/formatters/dprint.lua

The `dprint` cwd according to the docs:
> After [installing](https://dprint.dev/install), the main part of getting setup is to create a dprint.json/dprint.jsonc, or hidden .dprint.json/.dprint.jsonc file in your project.
> https://dprint.dev/setup/
I can confirm it has been tested on my local machine.

fix: set a cwd for dprint

---

lua/conform/formatters/djlint.lua

According to the docs:
> Configuration is done either through your projects pyproject.toml file, or a .djlintrc file.
> https://www.djlint.com/docs/configuration/

fix: set a cwd for djlint

---

lua/conform/init.lua

solves: https://github.com/stevearc/conform.nvim/issues/271
Turned out to be such a simple change... `opts.range` should just be `nil` when the whole buffer is selected.
cc @wookayin

feat: support lsp buffer formatting when formatting the whole file

---

lua/conform/formatters/biome.lua

According to the docs:
> The Biome configuration file is named `biome.json` and should be placed in the root directory of your project. The root directory is usually the directory containing your project’s `package.json`.
https://biomejs.dev/guides/how-biome-works/#configuration

fix: set a cwd for biome

---

lua/conform/formatters/swift_format.lua

`swift-format` won't pick up `.swift-format` config file in stdin mode. We need to set `stdin = false` and `--in-place` to make it work with `conform.nvim`.
[apple/swift-format/README.md](https://github.com/apple/swift-format/blob/e312ede68bd8549381f9e2edfef7e6c176e9a50e/README.md#L129-L131)
> *   `-i/--in-place`: Overwrites the input files when formatting instead of
printing the results to standard output. _No backup of the original file is
made before it is overwritten._
Fix https://github.com/stevearc/conform.nvim/issues/211

fix: `swift_format` doesn't respect `.swift-format` file

---

lua/conform/formatters/biome-check.lua

`biome` formatter uses `biome format` command which applies formatting but doesn't apply lint autofixes. Couldn't find a better way then to create another formatter that uses `biome check --apply-unsafe`

feat: add biome-check formatter

---

lua/conform/formatters/awk.lua

Add formatter for awk programs. Surprise! It's awk!

feat: add awk formatter

---

README.md
lua/conform/formatters/gersemi.lua

Since `cmake_format` has seemingly been completely abandoned, this would be great to have pre-configured.

Add configuration for `gersemi`

---

README.md
lua/conform/formatters/sqlfmt.lua

Fulfills #145.
Works with installing `sqlfmt` via e.g. `Mason` and adding optional configuration as:
```lua
"conform.nvim",
dev = true,
enabled = true,
event = { "BufWritePre" },
cmd = { "ConformInfo" },
opts = {
formatters_by_ft = {
sql = { "sqlfmt" },
},
formatters = {
sqlfmt = {
exe = "sqlfmt",
stdin = true,
args = { "-", "--fast", "--line-length", "120" },
},
},
},
```

feat: add formatter sqlfmt

---

README.md
lua/conform/formatters/tofu_fmt.lua

Adds `tofu_fmt` from [OpenTofu](https://opentofu.org). An alternative to `terraform_fmt` for those that have switched away from Terraform.

feat: add OpenTofu formatter

---

lua/conform/formatters/php_cs_fixer.lua

This adds the `cwd` option into the default php-cs-fixer options in order to honor project-level configuration.
`composer.json` should be the "safest" project root option here, since if a project doesn't have a `.php-cs-fixer.dist.php` or similar config file, it looks like we may accidentally use a parent config instead of the default config (currently used with these conform settings), which I believe would be different than typical php-cs-fixer behavior (i.e. use project-level config, or default)

fix: add cwd to honor project php-cs-fixer

---

lua/conform/formatters/swiftformat.lua

I noticed that `swiftformat` configuration is missing some details. 
I added support for range formatting + I specified how to find cwd.

feat: improved swiftformat configuration

---

README.md
doc/conform.txt
lua/conform/init.lua
lua/conform/runner.lua
scripts/options_doc.lua

|   |  PR  |                               Title                                |
| - | ---- | ------------------------------------------------------------------ |
| 1 | >332 | feat: add formatter config option to change name of temporary file |
| 2 | #333 | fix(phpcbf): use non-stdin formatting and customize tempfile name  |

[1/2] feat: add formatter config option to change name of temporary file

---

lua/conform/formatters/phpcbf.lua

|   |  PR  |                               Title                                |
| - | ---- | ------------------------------------------------------------------ |
| 1 | #332 | feat: add formatter config option to change name of temporary file |
| 2 | >333 | fix(phpcbf): use non-stdin formatting and customize tempfile name  |
fixes #289

[2/2] fix(phpcbf): use non-stdin formatting and customize tempfile name

---

lua/conform/formatters/sqlfluff.lua

Otherwise we get the following error `The -f/--force option is deprecated as it is now the default behaviour.`

Remove --force flag in sqlfluff since it's default now

---

README.md
doc/conform.txt
lua/conform/formatters/nimpretty.lua

Adds support for `nimpretty`, the official formatter for [nim](https://nim-lang.org/).

feat: add support for nimpretty

---

README.md
doc/conform.txt
lua/conform/formatters/crystal.lua

Adds support for the official [crystal](https://crystal-lang.org/) formatter.

feat: support crystal tool format

---

lua/conform/formatters/prettier.lua
lua/conform/formatters/prettierd.lua

Prettier supports ESM in their configuration, so I think it should be added to the supported config files.
**Commit:** https://github.com/prettier/prettier/commit/44d246a2a25473f65ab6be98cf5fe63d3ffe8f8d

feat(prettier, prettierd): add mjs files to supported config files

---

README.md
doc/conform.txt
lua/conform/formatters/inko.lua

This adds support for formatting Inko (https://inko-lang.org/) source files using the `inko fmt` command.

Add formatter for Inko

---

README.md
doc/conform.txt
lua/conform/formatters/clang-format.lua
lua/conform/formatters/clang_format.lua

This makes the formatter name consistent with the executable and also with other tools like e.g. Mason, for better interoperability.
One use-case is to be able to automatically install formatters that are registered with other tools like Mason.
```lua
local registered_formatters = require("conform").list_all_formatters()
for _, formatter in ipairs(registered_formatters) do
MasonInstall(formatter) -- Asume a MasonInstall function exists
end
```

refactor: Rename clang_format to clang-format

---

lua/conform/formatters/terraform_fmt.lua

Currently the `terraform_fmt` formatter outputs colors, resulting in "bad" characters in conform.log.
Example:
```
22:03:46[ERROR] Formatter 'terraform_fmt' error: [31m[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mAttribute redefined[0m
[31m│[0m [0m
[31m│[0m [0m[0m  on <stdin> line 3, in resource "test":
[31m│[0m [0m   3: 	[4mhello[0m = 123[0m
[31m│[0m [0m
[31m│[0m [0mThe argument "hello" was already set at <stdin>:2,3-8. Each argument may be
[31m│[0m [0mset only once.
[31m╵[0m[0m
[0m[0m
```
Adding the `-no-color` argument to `terraform fmt` will result in a more readable output:
```
22:13:44[ERROR] Formatter 'terraform_fmt' error: 
Error: Attribute redefined
on <stdin> line 3, in resource "test":
3: 	hello = 123
The argument "hello" was already …
```

Do not output colors in terraform_fmt

---

lua/conform/formatters/smlfmt.lua

This PR adds formatter support for [SML](https://www.smlnj.org/) using `smlfmt` (https://github.com/shwestrick/smlfmt).

Add formatter for SML (Standard ML)

---

lua/conform/formatters/biome-check.lua

This PR updates the **biome-check** formatter. The modification changes the default behavior from using unsafe code fix mode to safe code fix mode to enhance reliability and security when auto-correcting code. 
More details about the tool can be found at [biomejs.dev/linter](https://biomejs.dev/linter/).

fix(biome-check): use safe fixes

---

lua/conform/runner.lua

improve the fix of issue #274 and fix issue #360

fix: handle windows line ending when config.stdin is true

---

lua/conform/formatters/prettierd.lua

When formatting with `prettierd` on windows, even though the executable exists, there is the following error:
```
19:50:56[ERROR] Formatter 'prettierd' error in jobstart: Vim:E903: Process failed to start: no such file or directory: "C:/Users/myuser/mytest/node_modules/.bin/prettierd"
```
This PR adds detection and selection of `.cmd` executable on windows, the same way we do in `prettier.lua`, which fixes the above.

Correctly find prettierd executable on windows

---

lua/conform/util.lua

Thank you for maintaining this beautiful plugin. With the latest changes I have encountered a tiny bit of error therefore I have opened up this merge request.
It throws errors when the configured formater does not have a default.
```text
  Error  11:10:56 msg_show.lua_error Error detected while processing BufWritePre Autocommands for "*":
11:10:56 msg_show Error executing lua callback: vim/shared.lua:0: src: expected table, got nil
stack traceback:
[C]: in function 'error'
vim/shared.lua: in function 'validate'
vim/shared.lua: in function 'list_extend'
....local/share/nvim/lazy/conform.nvim/lua/conform/util.lua:142: in function 'computed_args'
...ocal/share/nvim/lazy/conform.nvim/lua/conform/runner.lua:29: in function 'build_cmd' …
```

Neovim 0.10 Compatible Functions Require a Default

---

lua/conform/formatters/mix.lua

This is more of a fix than a feature.
By adding the filename to `--stdin-filename`, `mix format` can detect the type of file. By default `--stdin-filename` is `stdin.exs` thus only allowing formatting of Elixir.
This change is needed to allow formatting for `mix format` plugins. Most notably the `heex` template files which are used in the Phoenix Framework, which comes with a `heex` plugin by default. (https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html)
The `mix format` behaviour is documented here: https://hexdocs.pm/mix/main/Mix.Tasks.Format.html#module-task-specific-options

feat: set mix format --stdin-filename

---

lua/conform/formatters/isort.lua

fix(isort): explicitly pass line endings

---

lua/conform/formatters/hcl.lua

Adds a generic formatter for `hcl` files.
I realize that there are already 2 formatters for hcl files defined in this repo, but to use either one of them, you need to have the specific tool installed (terraform or packer).
Meant to be used with the `hclfmt` binary that is built from the [hcl project](https://github.com/mason-org/mason-registry/blob/main/packages/hclfmt/package.yaml). This is also the one that can be obtained with mason: [registry link](https://github.com/mason-org/mason-registry/blob/main/packages/hclfmt/package.yaml).
Formats input from stdin and writes to stdout.

Add a generic hcl formatter (hclfmt)

---

README.md
doc/conform.txt
lua/conform/formatters/rustfmt.lua
lua/conform/formatters/yew-fmt.lua
lua/conform/util.lua

feat: add support for yew-fmt

---

README.md
doc/conform.txt
lua/conform/formatters/leptosfmt.lua

As title says: this adds support for leptosfmt 😀 
This is not the same as #363 since that suggestion does both leptosfmt and rustfmt combined. This commit just adds a leptos formatter, which can then be chained together sequentially with rustfmt in a conform config, if someone wants to do that.

feat: add support for leptosfmt

---

README.md
lua/conform/formatters/ruff_organize_imports.lua

This adds another `ruff` based formatter which tells it to organize imports. Useful for replacing `isort` with ruff. Neither the `ruff_fix` nor `ruff_format` cover this case or include it in their formatting.
Thanks in advance!

feat: add `ruff_organize_imports` formatter

---

lua/conform/formatters/dprint.lua

[Install - dprint - Code Formatter](https://dprint.dev/install/)
[dprint - npm](https://www.npmjs.com/package/dprint)
dprint is supports installation via npm, so I have also included node_modules in the search targets.

fix(dprint): add support node_modules

---

README.md
doc/conform.txt
lua/conform/formatters/format-queries.lua

I found out that nvim-treesitter comes with a formatter; that they themselves use to format their queries:\
https://github.com/nvim-treesitter/nvim-treesitter/blob/ea2b137f35fb1e87a6471ec311805920fdf45745/.github/workflows/lint.yml#L36-L51
They maintain it, and it [ships with the plugin](https://github.com/nvim-treesitter/nvim-treesitter/blob/ea2b137f35fb1e87a6471ec311805920fdf45745/scripts/format-queries.lua)... So why not use it?
I threw this a little hastily together; if you have some better ideas for the condition or anything else, please let me know :-)

[feat]: add treesitter query formatter

---

lua/conform/ft_to_ext.lua
lua/conform/runner.lua

the extension used to be always the file type, be smarter now. For instance prettier wouldn't recognize a `.typescript` extension.

unsaved files: smarter file name extension

---

README.md
doc/conform.txt
lua/conform/formatters/d2.lua

As `d2` filetype is not defined for nvim at the time, you may need to `set filetype=d2` for this to work

feat: add support for d2

---

README.md
doc/conform.txt
lua/conform/formatters/vsg.lua

Hi, love your project. This adds support for the [VHDL Style Guide](https://github.com/jeremiah-c-leary/vhdl-style-guide) (VSG) formatter.
The formatter doesn't auto-detect configuration files, so I added functionality to look for `.vsg.yaml` and `.vsg.json` in and under the file's directory and in `xdg-config/vsg` and `~/.config/vsg`. I couldn't find any mention of a standard name for said files in the documentation, but I saw some other people using these names and is also what I use myself. This might be out of scope, but it is quite nice to have, at least until they settle on something themselves or bake in the functionality. But please let me know what you think.

feat: add support for for vsg

---

README.md
doc/conform.txt
doc/recipes.md
lua/conform/init.lua
scripts/autoformat_doc.lua
scripts/options_doc.lua

This deprecates the `lsp_fallback` option (gracefully; it should continue to work) and replaces it with the `lsp_format` enum which can be several values. Three of the values produce behavior that was possible with `lsp_fallback`, and two of them are new behaviors. The new behaviors fix #316 
| lsp_format | lsp_fallback | description |
| -- | -- | -- |
| nil or "never" | nil or false | Do not use LSP formatting |
| "fallback" | true | Use LSP formatting if there are no formatters configured for this filetype |
| "prefer" | - | Use LSP formatting when it is available, otherwise fall back to the formatters configured for this filetype |
| "last" | "always" | Run configured formatters, then run LSP formatting |
| "first" | - | Run LSP formatting, then run configured formatters |

feat!: expand options for LSP formatting

---

lua/conform/formatters/djlint.lua

Formatter now able to use local buffer tabstop config. One of the case is when the tabstop is set by editorconfig.
Close #457

feat(djlint): respect local buffer tabstop config

---

lua/conform/formatters/biome-check.lua

biome deprecated --apply.
```
--apply   Alias for `--write`, writes safe fixes, formatting and import sorting 
(deprecated, use `--write`)
```

fix(biome-check): use --write instead of deprecated --apply

---

README.md
lua/conform/formatters/swiftlint.lua

I've added [swiftlint](https://github.com/realm/SwiftLint) as a formatter, I've tested over the weekend and it works great.
The command used to format is as follows:
```sh
swiftlint lint \
--use-stdin \ # take input from stdin
--fix \ # automatically fix errors where possible
--format # apply sourcekit lsp default formatting if available
```

Adds Swiftlint formatter

---

lua/conform/formatters/djlint.lua
lua/conform/formatters/markdown-toc.lua
lua/conform/formatters/shfmt.lua
lua/conform/runner.lua
lua/conform/types.lua
tests/runner_spec.lua

This adds the automatic setting of `-i` so that `shfmt` follows the current indentation settings of neovim. Whether it is manually set by the user or set through external factors such as `.editorconfig`
I also checked to see if this is done elsewhere for other formatters and found a couple others which I was able to improve the "correctness" of their indentation size calculations
EDIT: I was thinking about this and it seems like having the effective `shiftwidth` value is quite nice. And because this seems to be "contextual information" it seemed natural to put it in the `conform.Context` type since it is virtually free to calculate performance wise. Let me know if you disagree. Another approach would be to make some sort of utility module that is imported by formatters on an as needed …

feat(shfmt): add automatic indentation detection

---

README.md
doc/conform.txt
lua/conform/formatters/markdownfmt.lua

Adding support for markdownfmt. I opted to not include `find_executable` in the command since it's installed via `go install`, and gopath might differ between machines.
I have tested it and it seem to be working fine as long as the executable is reachable from PATH.

feat: add support for markdownfmt

---

README.md
doc/conform.txt
lua/conform/formatters/nixfmt-rfc-style.lua
lua/conform/formatters/nixfmt.lua

This is different from `nixfmt`, which is currently defined at:
https://github.com/stevearc/conform.nvim/blob/25d48271e3d4404ba017cb92a37d3a681c1ad149/lua/conform/formatters/nixfmt.lua
This new formatter is meant to eventually replace `nixfmt`. More information can be found on [their repo](https://github.com/NixOS/nixfmt)

feat(formatters): add nixfmt-rfc-style

---

lua/conform/formatters/djlint.lua

When we pass cli arguments to `djlint`, they override those set in the configuration files: https://www.djlint.com/docs/configuration
I'd expect the formatter to respect the configuration file. If a user wants to override they can do so https://github.com/stevearc/conform.nvim/issues/457#issuecomment-2169139931.
This PR reverts the changes made in #467.

Remove indent command line argument for djlint

---

lua/conform/formatters/docformatter.lua

Fixes error `Formatter 'docformatter' error: unknown error` 
According to the [documentation](https://docformatter.readthedocs.io/en/latest/usage.html) on possible exit_codes: 
> 3 - if any file needs to be formatted (in --check or --in-place mode)
Which is expected when the document needs actual formatting

fix(docformatter): update exit_codes, 3 is correct in in-place formatting

---

lua/conform/formatters/sqlfluff.lua

Assuming the ANSI dialect may lead to parsing errors when using syntax specific to some dialect, so it shouldn't be the default. Therefore, a config is mandatory, to select the dialect.
We can't just update the exit codes because `sqlfluff` straight up refuses to format with some erros. For instance, I was getting:
```
WARNING    Fixes for LT09 not applied, as it would result in an unparsable file. Please report this as a bug with a minimal query which demonstrates this warning.                                                                             
WARNING    One fix for LT09 not applied, it would re-cause the same error. …
```

fix(sqlfluff): don't assume ansi dialect and require config

---

.github/workflows/tests.yml
README.md
lua/conform/errors.lua
lua/conform/init.lua
lua/conform/runner.lua
lua/conform/util.lua
tests/runner_spec.lua
tests/util_spec.lua

Use `vim.system` instead of `vim.fn.jobstart` for performance gains (#191)
`black` before:
`black` after:

refactor: use vim.system

---

README.md
doc/conform.txt
lua/conform/formatters/superhtml.lua
lua/conform/formatters/ziggy.lua
lua/conform/formatters/ziggy_schema.lua

Add support for formatters used (and created) by the zine static site generator
project:
- [Zine](https://github.com/kristoff-it/zine)
- [SuperHTML](https://github.com/kristoff-it/superhtml)
- [Ziggy](https://github.com/kristoff-it/ziggy)

feat(zine): add superhtml and ziggy support

---

lua/conform/log.lua

This helps people better distinguish whether a log line is fresh or aged.

fix(log): prepend date to log lines

---

.envrc

added an example `.direnvrc` since i ran into this error
```
direnv: loading ~/dev/conform.nvim/.envrc
environment:860: python: command not found
direnv: Could not find python's version
./.envrc:2: pip: command not found
```

chore: add example layout python for direnv

---

lua/conform/formatters/deno_fmt.lua

I completed the `deno_fmt` extensions table with the [table of supported extensions in Deno's documentation](https://docs.deno.com/runtime/reference/cli/formatter/#supported-file-types). I added a couple of stable extensions that needed to be included.
Three unstable ones were also absent: Astro, Svelte, and Vue. These require the `--unstable-component` flag to work. If you don't provide the flag, the `deno fmt` command exists successfully (code 0) but does nothing.  Should the code here be refactored so that an info/warning/error message is logged if you format one of these files without the flag to improve debugging?
The [unstable-component flag documentation](https://docs.deno.com/runtime/reference/cli/formatter/#formatting-options-unstable-component) mentions that Angular files are …

Add missing deno_fmt extensions

---

README.md
doc/conform.txt
lua/conform/formatters/nginxfmt.lua

I saw nginx is very popular web server and is used widely, but there aren't any support for its config file now, so i add it. The config file without formatting is definitely a mess.
The doc is [here](https://github.com/slomkowski/nginx-config-formatter).

feat: add support for nginx-config-formatter

---

README.md
doc/conform.txt
lua/conform/formatters/standard-clj.lua

Adding support for [`standard-clj`](https://github.com/oakmac/standard-clojure-style-js).
The filename differs from the other standard linters, but wanted to preserve the command name.
(thanks for conform btw 🍻)

Add support for Clojure standard-clj

---

lua/conform/formatters/mix.lua

the current folder should be the project folder. There could be per-subfolder .formatter.exs files but you're not meant to run the formatter from such folders.
I ran into this exact issue:
https://elixirforum.com/t/formatter-error-in-phoenix-migrations-cant-find-ecto-sql/28764/10
This issue also happened in other editors, as can be seen in the link. The previous behavior would work fine if there was no .formatter.exs in subfolders or if these didn't rely on dependencies provided by the project-level mix.exs.
I also checked the documentation regarding the elixir formatting task:
https://hexdocs.pm/mix/1.12/Mix.Tasks.Format.html
In that documentation it's written:
```markdown
. If such option is not yet available in your editor of choice, adding the required integration is usually a matter …
```

elixir mix: fix for current folder for execution

---

lua/conform/runner.lua

If the `basename` contains `%` characters, that line fails.
This fixes that.
Fixes https://github.com/folke/snacks.nvim/issues/187

fix(runner): replace `$FILENAME` last, since it can contain `%` which would fail when `gsub` `$RANDOM`

---

README.md
doc/conform.txt
lua/conform/formatters/awk.lua
lua/conform/formatters/gawk.lua

I made a similar pull request in mfussenger/nvim-lint ([#684]) a while back.
Same as in that case, gawk is more or less the only awk implementation that
supports formatting of awk files, thus I find it make sense to have the
formatter named gawk instead. Could also prevent problems for people who use
Alpine as an example, which by default uses Busybox's awk implementation, but
still would like to have an awk formatter configured for when gawk is available.
[#684]: https://github.com/mfussenegger/nvim-lint/pull/684

Rename awk formatter to gawk

---

lua/conform/formatters/buildifier.lua

When editing a file named BUILD, the command `buildifier` was executed, but the file in the editor was not reformatted properly.
If I'd run `buildifier [path-to-file]`, the file would be reformatted as expected, so the formatter works as expected in this case.
After experimenting a bit, I came up with the new command line I propose in this change. It still sends the code via stdin to `buildifier`, but now is aware of the path the file has in the project. This seems to have an influence on the behavior of `buildifier`.
See `buildifier --help`:
```
-type string
Input file type: build (for BUILD files), bzl (for .bzl files),
workspace (for WORKSPACE files), default (for generic Starlark
files) or auto (default, based on the filename) (default "auto")
```

Fix buildifier formatting of BUILD file

---

lua/conform/formatters/biome-organize-imports.lua

Hello!
This PR adds another biome formatter, to **only** organize imports (in a similar manner to ruff, with ruff's [organize-imports](https://github.com/stevearc/conform.nvim/blob/master/lua/conform/formatters/ruff_organize_imports.lua)).
The major reason for another formatter is that there are some [known limitations](https://biomejs.dev/internals/language-support/#html-super-languages-support) when using biome's regular formatter with HTML super languages, such as Svelte and Vue.

feat: biome organize imports

---

lua/conform/init.lua
plugin/conform.lua

There is little to no benefit to create `ConformInfo` only if the user calls the setup function since you can use this plugin without never calling it.

fix: create ConformInfo regardless of setup

---

lua/conform/formatters/format-queries.lua

`scripts/format-queries.lua` live in https://github.com/nvim-treesitter/nvim-treesitter repository.
Those who lazy load this plugin should require it before searching the `rtp`.

fix(format-queries): require nvim-treesitter before scaning rtp

---

README.md
doc/conform.txt
lua/conform/formatters/css_beautify.lua
lua/conform/formatters/html_beautify.lua
lua/conform/formatters/js_beautify.lua

Added [js-beautify](https://github.com/beautifier/js-beautify) to conform.nvim, using [stdin](https://github.com/beautifier/js-beautify#options)
I took inspiration from the prettier config; though I haven't actually tested the "fs.is_windows and js-beautify.cmd" part (I don't have a Windows to test on)
js-beautify comes with two extra bins: `html-beautify` and `css-beautify`; which is just a [an easy interface](https://github.com/beautifier/js-beautify?tab=readme-ov-file#css--html) to `js-beautify` (passing in `--html` and `--css` respectively)
What do you think is the best way to implement this? They all take the same basic arguments, as such the 3 different implementations I made currently are all copy/paste, except for the binary name
Let me know what you think :-)

feat: added js-beautify (w/ css- & html-beautify)

---

README.md
lua/conform/formatters/sqruff.lua

[sqruff](https://github.com/quarylabs/sqruff) is a promising new tool, that combines the speed of `ruff` with usefulness of `sqlfluff`
This implementation is heavily inspired by the [sqlfluff](https://github.com/stevearc/conform.nvim/blob/master/lua/conform/formatters/sqlfluff.lua) implementation (they are pretty much identical)
While sqruff works without a `.sqruff` file, it hardly makes sense to do so. So I've kept the enforcement of cwd

feat: added sqruff

---

lua/conform/runner.lua

This is a feature I've added to my local copy of `conform.nvim` which I wondered if you would be interested in adding! I would've created and issue instead but I thought I'd just do a PR instead as I had already made the changes locally.
Auto command triggers for `ConformPreFormatter` and `ConformPostFormatter` which fire before and after each formatter that is called. This allows hooking into the format process for each formatter.
I've added this as the formatters I have to run for work can sometimes take a while and there doesn't seem to be any feedback as to which formatter is currently running. 
Adding these hooks enables me to have the following auto commands:
```lua
vim.api.nvim_create_autocmd("User", {
pattern = 'ConformPreFormatter',
callback = function(event)
print('running ' .. …
```

feat: add pre and post formatter hooks

---

README.md
lua/conform/formatters/pyproject-fmt.lua

This adds support for [pyproject-fmt](https://github.com/tox-dev/toml-fmt/tree/main/pyproject-fmt) which is used to format `pyproject.toml` files in a Python project

feat: added pyproject-fmt

---

README.md
lua/conform/formatters/hurlfmt.lua

Adds the `hurlfmt` formatter for hurl files.
See: 
- https://hurl.dev/
- https://github.com/Orange-OpenSource/hurl/blob/master/docs/manual/hurlfmt.md

feat: add hurlfmt (hurl files)

---

lua/conform/formatters/styler.lua

Currrently the styler command in conform relies on the user using R.nvim and having the associated r package installed. However, under the hood, r.nvim just calls styler directly. I have updated the default styler configuration to do the same. I have also added some comments describing usage. This is related to #275.

use styler natively for R instead of calling it via r.nvim::format

---

README.md
doc/conform.txt
lua/conform/formatters/codeql.lua

Added support for the codeql query formatter. Documentation can be found [here](https://docs.github.com/en/code-security/codeql-cli/codeql-cli-manual/query-format)

feat: add codeql native formatter

---

lua/conform/formatters/runic.lua

This adds support for [Runic.jl](https://github.com/fredrikekre/Runic.jl) -- a code formatter for Julia source code.

feat: add runic formatter

---

lua/conform/lsp_format.lua

Catch the "undojoin after undo" error the same way as the other call to `vim.cmd.undojoin`.

fix: fix uncaught undojoin after undo error

---

lua/conform/formatters/cabal_fmt.lua

A comment like
```cabal
-- cabal-fmt: expand src/
```
cannot be processed without a file path, which means the filename needs
to be passed as input.

Enable cabal-fmt to process expand pragmas

---

lua/conform/formatters/prettypst.lua

This tells prettypst to use stdin and stdout for the formatting. Before it errored out and did not format the buffer.

fix(prettypst): stdin and stdout args

---

lua/conform/formatters/latexindent.lua

When ran with the `-l` flag and no other filename (as is the case when passing the file through STDIN), latexindent interprets the argument to `-l` as the file to be formatted
Eg. `latexindent -l=foo.yaml < bar.tex` overwrites the current buffer with `foo.yaml` rather than the formatted `bar.tex`
This commit just appends the argument `-` so that STDIN is always used
See: `f2063898e943893b20aeb30a324d5364ebaddff6` (#654)
Note: Issue can be replicated by passing the following option to `setup`:
```
formatters = {
latexindent = {
prepend_args = { "-l=foo.yaml" },
},
},
```
The formatter will overwrite the buffer with the attempted formatting of `foo.yaml` if it exists, and just error out if it doesn't

fix(latexindent): regression in `f2063898e9`

---

lua/conform/formatters/sqruff.lua

The arg "--force" must be used for auto formatting, otherwise it logs error in ConformInfo when trying to format.
Reading from stdin seams not working,
thus stdin is set to false and "$FILENAME" is used instead.
sqruff doesn't require cwd (the ".sqruff" file).
Without ".sqruff", it uses the default config.

fix(sqruff): update args, stdin and require_cwd

---

README.md
doc/conform.txt
lua/conform/formatters/dioxus.lua

i prefer to use it with `require_cwd = true` and the config snippet below, but i think they're too much of a personal preference to include in the pr
```lua
formatters_by_ft.rust = function()
if vim.fn.executable("dx") == 1 then
return { "rustfmt", "dioxus" }
end
return { "rustfmt" }
end
```

formatters: add dioxus (`dx fmt`)

---

lua/conform/formatters/cljstyle.lua

`cljstyle` uses a hierarchy of `.cljstyle` configuration files in the source tree to change formatting behavior, so if it is run in the wrong directory the formatting may be incorrect.
This sets the cwd to one that contains a `.cljstyle` file.
https://github.com/greglook/cljstyle?tab=readme-ov-file#configuration

Add .cljstyle as the root file for cljstyle formatter

---

lua/conform/formatters/pyupgrade.lua

feat: add pyupgrade

---

lua/conform/formatters/csharpier.lua

Since the `1.0.0` release of csharpier, the CLI has changed and the `format` 
command is required. Moreover, the `--write-stdout` option is implicit when the 
content comes from stdin, and therefore can be removed.
BREAKING-CHANGE: The new arguments for the CLI require csharpier
`>= 1.0.0`.

fix(csharpier)!: use csharpier format command

---

README.md
lua/conform/formatters/pymarkdownlnt.lua

[pymarkdownlnt] is the python equivalent to the obiquitous markdownlint. For python projects, it makes more sense to use the former in order to avoid pulling Node.js and its dependencies. Add it to the official formatters.
[pymarkdownlnt]: https://github.com/jackdewinter/pymarkdown

feat(formatters): add pymarkdownlnt

---

README.md
doc/conform.txt
lua/conform/formatters/ghdl.lua

This PR adds GHDL <https://github.com/ghdl/ghdl>, using its `fmt` command. It requires a filename arg, but it only prints to stdout, hence no `stdin = false` yet `$FILENAME` in `args`.
I guess the `--std=08` flag can be questioned, but that is what I used for the GHDL linter in nvim-lint <https://github.com/mfussenegger/nvim-lint/blob/master/lua/lint/linters/ghdl.lua>. I'm no expert but I believe VHDL 2008 to be mostly backward compatible, and formatting on most of my files fails without the flag. Also that's 17 years... But say if you want to omit.

feat: add support for ghdl

---

lua/conform/init.lua

Currently the `opts.range` argument is overwritten if the current mode is `V`.
This is due to missing logical grouping brackets on the `or` branch of the or check.

Don't overwrite given range with current selection

---

lua/conform/formatters/terragrunt_hclfmt.lua

This is updating the way `terragrunt_hclfmt` performs formatting as recent updates to Terragrunt did deprecate the `hclfmt` command. The new way to perform the formatting is to use the new `hcl fmt` command.
The documentation can be found here: https://terragrunt.gruntwork.io/docs/reference/cli/commands/hcl/fmt/

Update Terragrunt format command

---

lua/conform/util.lua

Should fix #784
```toml
[package]
name = "conform-repro"
version = "0.1.0"
edition = "2024"  # the match statement should take into account the number quotes
edition = 2024  # this is an invalid cargo.toml 
```

fix(rust): edition match

---

lua/conform/formatters/csharpier.lua

`:ConformInfo` failed for me because i have `csharpier` installed via `mason.nvim`, but have no `dotnet` on my working machine
This commit adds a check for this case while keeping the local `csharpier` available

fix(csharpier): check if the dotnet command is available
